[[mainPEP]]
= Policy Enforcement Point (PEP)

Refer to PEP building block documentation - https://eoepca.github.io/um-pep-engine/master

== Description

The Policy Enforcement Point (PEP) allows unsecured Resource Servers to be integrated in the architecture, by providing the means to securely register, manage and expose resources. Any Web Service provided by the architecture can potentially run an ad-hoc PEP service that serves as secure contact point and handles all the necessary UMA Flow steps.

== Context

The following context diagram identifies the major components interfacing with the PEP: +
([red]#RED# ~ consumers of PEP provided interfaces, [blue]#BLUE# ~ providers of interfaces consumed by the PEP)

[.text-center]
[#img_pepContext,reftext='{figure-caption} {counter:figure-num}']
.Policy Enforcement Point context diagram
[plantuml, pep-context, png] 
....
include::include/pep-context.wsd[]
....

EOEPCA PEP Service provides a Platform Resource management API that abstracts the UMA Standard and facilitates its usage by Resource Owners. It also exposes unsecured endpoints of Resource Servers through its secure proxying endpoint.

The PEP relies on UMA to implement the necessary steps of the ticket-based authorization flow. It also allows propagation of End-User claims towards the Resource Server.

== Provided Interfaces

[.text-center]
[#img_pepProvidedInterfaces,reftext='{figure-caption} {counter:figure-num}']
.Policy Enforcement Point provided interfaces
[plantuml, pep-provided-interfaces, png] 
....
include::include/pep-provided-interfaces.wsd[]
....

=== Platform Resource API

==== Applicable Standards

No applicable standards besides Hypertext Transfer Protocol (HTTP) and a RESTful API approach allowing CRUD operations over Resource reference objects.

==== Endpoints

URL: /resources/{id}

=== Secured Proxy

==== Applicable Standards

No applicable standards besides the capability to parse and enrich Hypertext Transfer Protocol (HTTP) operations .

==== Endpoints

URL: /secure/{back-end-url}

== Required Interfaces

[.text-center]
[#img_pepRequiredInterfaces,reftext='{figure-caption} {counter:figure-num}']
.Policy Enforcement Point required interfaces
[plantuml, pep-required-interfaces, png] 
....
include::include/pep-required-interfaces.wsd[]
....

=== OIDC Authentication

The PEP utilizes an OIDC Client implementation to consume OIDC endpoints, authenticate itself as trusted platform component, generate JWT documents containing End-User information, and secure its Platform Resource API endpoints.

==== Applicable Standards

* IETF - OpenID Connect 1.0 

==== Remote Endpoints

URL: <um-login-service>/.well-known/openid-configuration

The Login Service exposes the standard discovery document, a JSON showcasing all the necessary metadata and endpoint enumeration for a client application to dynamically load all the needed endpoints.

=== UMA Authorization

The PEP utilizes a UMA Client implementation to consume UMA Endpoints, enforcing authorization of all requests made to the secure proxy endpoint (generation of tickets and RPT validation)

==== Applicable Standards

* Kantara Innitiative - UMA 2.0 

==== Remote Endpoints

URL: <um-login-service>/.well-known/uma2-configuration

The Login Service exposes a dicovery document very much similar to OIDC well-known documents. Although this is not implicitly stated as necessary part of a UMA-compliant solution, serving a well-known endpoint makes client integration more familiar to developers that may be used to OIDC Client integration.

=== Protected Resource Server

The PEP sits in front of a Resource Server and propagates all requests and responses (acting as an intermediate client). The only modifications performed by the PEP consist in the inclusion of an HTTP Header containing relevant End-User information. 

==== Applicable Standards

No applicable standards besides the capability to parse and enrich Hypertext Transfer Protocol (HTTP) responses.

==== Remote Endpoints

The endpoint protected by the PEP is a configurable parameter and depends on the characteristics of the Resource Server running behing the PEP.

== Example Scenarios

=== Resource Access
=== Resource Management

