@startuml component

hide stereotype

skinparam component<<tbd>> {
    BackgroundColor Crimson
    FontColor white
}

skinparam node<<tbd>> {
    BackgroundColor Crimson
    FontColor white
}

skinparam component<<3rd>> {
    BackgroundColor CornFlowerBlue
    BorderColor DarkBlue
}

skinparam component<<reuse>> {
    BackgroundColor Khaki
    BorderColor Orange
}

skinparam node<<reuse>> {
    BackgroundColor Khaki
    BorderColor Orange
}

skinparam interface<<ext>> {
    BackgroundColor Red
    BorderColor Crimson
}

skinparam interface<<dep>> {
    BackgroundColor Blue
    BorderColor Navy
}

package "EOEPCA"{


    node "Execution Management\nService (EMS)" as ems <<reuse>> {

    }

    () "WPS 1.0 & 2.0" as wpsapi <<ext>>
    () "OGC API Processes" as ogcapi <<ext>>

    node "ADES" as ades {
        component "Web Processing\nServices" <<tbd>> as wps
        component Services <<tbd>> as services
    }

    wps -up- wpsapi
    wps -up- ogcapi

    () "ADES Proxy" as adespep
    node "UM-IAM" as iam {
        component "PEP" as pep <<3rd>>
        pep -left- adespep
        component "OIDC" as oidc <<3rd>>
    }
    () "Auth" as authz <<dep>>

    oidc -down- authz

    ems --( adespep
    pep --( wpsapi
    pep --( ogcapi

    services -up-( authz

    () "Resources API" as rmapi <<dep>>

    node "Resource Manager" as rm <<3rd>> {
        collections "Resources" as resources
    }

    rm -up- rmapi
    services -down-( rmapi

    () "Kubernetes API" as k8sapi <<dep>>

    cloud "Processing Cluster" as pc <<3rd>> {
        collections "Pods" as pods
    }

    pc -up- k8sapi
    services -down-( k8sapi


}

@enduml