@startuml component

hide stereotype

component "ADES" as ades <<ades>>
() "WPS 1.0 & 2.0" as wpsapi <<provided>>
ades -up- wpsapi
() "OGC API Processes" as ogcapi <<provided>>
ades -up- ogcapi
() "app-invocation" as invoke <<provided>>
ades -down- invoke

component "EMS" as ems <<consumer>>
ems -down-( wpsapi
ems -down-( ogcapi

component "User App" as userapp <<consumer>>
  userapp -up-( invoke

skinparam component<<ades>> {
    BackgroundColor #77ff77
    BorderColor #007700
}

skinparam interface<<provided>> {
    BackgroundColor #ff7777
    BorderColor #770000
}

skinparam component<<consumer>> {
    BackgroundColor #ff7777
    BorderColor #770000
}

@enduml
