@startuml component

hide stereotype

component PDP <<pdp>>
() "Platform Policy API" as pdpendpoints <<provided>>
() "XACML Policy Checks" as xacml_checks <<provided>>
PDP -down- pdpendpoints
PDP -down- xacml_checks

component "Login Service" as login_service <<consumer>>
component "Client Application" as client_app <<consumer>>
login_service -up-( pdpendpoints
client_app -up-( xacml_checks

  
skinparam component<<pdp>> {
    BackgroundColor #77ff77
    BorderColor #007700
}

skinparam interface<<provided>> {
    BackgroundColor #ff7777
    BorderColor #770000
}

skinparam component<<consumer>> {
    BackgroundColor #ff7777
    BorderColor #770000
}

@enduml
