@startuml component

hide stereotype

component PEP <<pep>>
() "PEP Endpoints" as pependpoints <<provided>>
PEP -down- pependpoints

component "Client Application" as client <<consumer>>
client -up-( pependpoints

  
skinparam component<<pep>> {
    BackgroundColor #77ff77
    BorderColor #007700
}

skinparam interface<<provided>> {
    BackgroundColor #ff7777
    BorderColor #770000
}

skinparam component<<consumer>> {
    BackgroundColor #ff7777
    BorderColor #770000
}

@enduml
