@startuml
autonumber
participant Client
participant "PEP" as PEP
participant "Resource Server" as RS
participant "Login Service" as AuthzAPI
participant "PDP" as PDP
Client -> RS: GET resource
PEP -> PEP: Resolve Resource ID
PEP -> AuthzAPI: Request Ticket (resource_id)
AuthzAPI --> PEP: return (ticket)
PEP --> Client: 401 Unauthorized (ticket)
Client -> AuthzAPI: POST /token (+ticket, +id_token)
AuthzAPI -> PDP: Policy Check
alt policy_check = ok
    PDP --> AuthzAPI: return "Permit"
    AuthzAPI --> Client: return (RPT)
    Client -> PEP: GET resource (RPT)
    PEP -> AuthzAPI : Check RPT status (PAT,RPT)
    alt rpt_status = ok
        AuthzAPI --> PEP: OK
        PEP -> RS: GET resource
        RS --> PEP: return (resource)
        PEP --> Client: return (resource)
    else rpt_status = ko
        AuthzAPI --> PEP: KO
        PEP --> Client: return 401 ("Expired token")
    end
    
else policy_check = ko
    PDP --> AuthzAPI: return "Deny"
    AuthzAPI --> Client: return 401 ("Denied by Policy")
end
@enduml